export const GET_HISTORYCAL_CHART="GET_HISTORYCAL_CHART"
export const GET_HISTORYCAL_CHART_FAILURE="GET_HISTORYCAL_CHART_FAILURE"


export const GET_COIN_LIST = 'GET_COIN_LIST';
export const GET_COIN_LIST_FAILURE = 'GET_COIN_LIST_FAILURE';